package ui.theme

import androidx.compose.ui.graphics.Color
import extensions.lightenColor

object ColorPalette {

    fun basic(isSystemInDarkTheme: Boolean): MyColors = MyColors(
        primary = ultraMarineBlue,
        secondary = ultraMarineBlue,
        background = if (isSystemInDarkTheme) darkGunMetal else twilightBlue,
        onPrimary = if (isSystemInDarkTheme) Color.White else Color.Black,
        onBackground = if (isSystemInDarkTheme) Color.White else Color.Black,
        isLight = !isSystemInDarkTheme,
        isDarkStatusBarIcons = !isSystemInDarkTheme,
        isDarkNavigationBarIcons = !isSystemInDarkTheme,
        card = if (isSystemInDarkTheme) eerieBlack else Color.White,
        cardMainContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        cardSecondaryContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        topBarTitle = if (isSystemInDarkTheme) Color.Black else Color.White,
        topBarIcons = if (isSystemInDarkTheme) Color.Black else Color.White,
        startButtonColor = parisGreen,
        pauseButtonColor = seaSerpert,
        resetButtonColor = cranberry,
        listCard = if (isSystemInDarkTheme) eerieBlack else Color.White,
        navBar = if (isSystemInDarkTheme) eerieBlack else Color.White,
        unselectedNavBarItemColor = if (isSystemInDarkTheme) spanishGrey else concord,
    )

    fun turquoise(isSystemInDarkTheme: Boolean): MyColors = MyColors(
        primary = eucalyptus,
        secondary = eucalyptus,
        background = if (isSystemInDarkTheme) darkGunMetal else twilightBlue,
        onPrimary = if (isSystemInDarkTheme) Color.White else Color.Black,
        onBackground = if (isSystemInDarkTheme) Color.White else Color.Black,
        isLight = !isSystemInDarkTheme,
        isDarkStatusBarIcons = !isSystemInDarkTheme,
        isDarkNavigationBarIcons = !isSystemInDarkTheme,
        card = if (isSystemInDarkTheme) eerieBlack else Color.White,
        cardMainContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        cardSecondaryContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        topBarTitle = if (isSystemInDarkTheme) Color.Black else Color.White,
        topBarIcons = if (isSystemInDarkTheme) Color.Black else Color.White,
        startButtonColor = parisGreen,
        pauseButtonColor = vodka,
        resetButtonColor = carnationPink,
        listCard = if (isSystemInDarkTheme) eerieBlack else Color.White,
        navBar = if (isSystemInDarkTheme) eerieBlack else Color.White,
        unselectedNavBarItemColor = if (isSystemInDarkTheme) spanishGrey else concord,
    )

    fun jasmine(isSystemInDarkTheme: Boolean): MyColors = MyColors(
        primary = jasmine,
        secondary = jasmine,
        background = if (isSystemInDarkTheme) darkGunMetal else Color.White,
        onPrimary = if (isSystemInDarkTheme) Color.White else Color.Black,
        onBackground = if (isSystemInDarkTheme) Color.White else Color.Black,
        isLight = !isSystemInDarkTheme,
        isDarkStatusBarIcons = !isSystemInDarkTheme,
        isDarkNavigationBarIcons = !isSystemInDarkTheme,
        card = if (isSystemInDarkTheme) eerieBlack else lotion,
        cardMainContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        cardSecondaryContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        topBarTitle = if (isSystemInDarkTheme) Color.Black else Color.White,
        topBarIcons = if (isSystemInDarkTheme) Color.Black else Color.White,
        startButtonColor = pistachio,
        pauseButtonColor = violetBlue,
        resetButtonColor = carnationPink,
        listCard = if (isSystemInDarkTheme) eerieBlack else lotion,
        navBar = if (isSystemInDarkTheme) eerieBlack else Color.White,
        unselectedNavBarItemColor = if (isSystemInDarkTheme) spanishGrey else concord,
    )

    fun sunShade(isSystemInDarkTheme: Boolean): MyColors = MyColors(
        primary = philippineOrange,
        secondary = philippineOrange,
        background = if (isSystemInDarkTheme) firefly else Color.White,
        onPrimary = if (isSystemInDarkTheme) Color.White else Color.Black,
        onBackground = if (isSystemInDarkTheme) Color.White else Color.Black,
        isLight = !isSystemInDarkTheme,
        isDarkStatusBarIcons = !isSystemInDarkTheme,
        isDarkNavigationBarIcons = !isSystemInDarkTheme,
        card = if (isSystemInDarkTheme) darkSlateGrey else desertStorm,
        cardMainContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        cardSecondaryContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        topBarTitle = if (isSystemInDarkTheme) Color.Black else Color.White,
        topBarIcons = if (isSystemInDarkTheme) Color.Black else Color.White,
        startButtonColor = pistachio,
        pauseButtonColor = crystalBlue,
        resetButtonColor = persimmon,
        listCard = if (isSystemInDarkTheme) darkSlateGrey else desertStorm,
        navBar = if (isSystemInDarkTheme) darkSlateGrey else desertStorm,
        unselectedNavBarItemColor = if (isSystemInDarkTheme) spanishGrey else concord,
    )

    fun marineBlue(isSystemInDarkTheme: Boolean): MyColors = MyColors(
        primary = dandalion,
        secondary = dandalion,
        background = if (isSystemInDarkTheme) japaneseIndigo else pictonBlue,
        onPrimary = if (isSystemInDarkTheme) Color.White else Color.Black,
        onBackground = Color.White,
        onCard = if (isSystemInDarkTheme) Color.White else Color.Black,
        isLight = !isSystemInDarkTheme,
        isDarkStatusBarIcons = !isSystemInDarkTheme,
        isDarkNavigationBarIcons = !isSystemInDarkTheme,
        card = if (isSystemInDarkTheme) dirtyBlue else Color.White,
        cardMainContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        cardSecondaryContent = if (isSystemInDarkTheme) Color.White else Color.Black,
        topBarTitle = if (isSystemInDarkTheme) Color.Black else Color.White,
        topBarIcons = if (isSystemInDarkTheme) Color.Black else Color.White,
        startButtonColor = if (isSystemInDarkTheme) urobilin else dandalion,
        pauseButtonColor = if (isSystemInDarkTheme) urobilin else dandalion,
        resetButtonColor = if (isSystemInDarkTheme) purpureus else purpleFlower,
        listCard = if (isSystemInDarkTheme) dirtyBlue else Color.White,
        navBar = if (isSystemInDarkTheme) dirtyBlue else steelBlue,
        unselectedNavBarItemColor = if (isSystemInDarkTheme) spanishGrey else concord,
    )

    fun outerSpace(isSystemInDarkTheme: Boolean): MyColors = MyColors(
        primary = outerSpace.lightenColor(.4),
        secondary = outerSpace,
        background = if (isSystemInDarkTheme) darkGunMetal else Color.White,
        onPrimary = if (isSystemInDarkTheme) Color.White else outerSpace,
        onBackground = if (isSystemInDarkTheme) Color.White else outerSpace,
        isLight = !isSystemInDarkTheme,
        isDarkStatusBarIcons = false,
        isDarkNavigationBarIcons = false,
        card = if (isSystemInDarkTheme) eerieBlack else brightGray,
        cardMainContent = if (isSystemInDarkTheme) Color.White else outerSpace,
        cardSecondaryContent = if (isSystemInDarkTheme) Color.White else outerSpace,
        topBar = if (isSystemInDarkTheme) eerieBlack else outerSpace,
        topBarTitle = if (isSystemInDarkTheme) outerSpace else Color.White,
        topBarIcons = if (isSystemInDarkTheme) outerSpace else Color.White,
        startButtonColor = outerSpace,
        pauseButtonColor = outerSpace,
        resetButtonColor = outerSpace,
        listCard = if (isSystemInDarkTheme) eerieBlack else brightGray,
        navBar = if (isSystemInDarkTheme) eerieBlack else outerSpace,
        unselectedNavBarItemColor = if (isSystemInDarkTheme) spanishGrey else concord,
    )
}
